# =============================================================================
# exporter.py — Iqra Digital Library v2
# =============================================================================
# export_books_pdf
# ----------------
# Converts a list of canonical book dicts into a styled PDF using fpdf2.
# Output is written to artifacts/export_<timestamp>.pdf.
# =============================================================================

from __future__ import annotations

import logging
from datetime import datetime
from typing import Any

from fpdf import FPDF

from .config import settings

logger = logging.getLogger(__name__)


def _safe_str(value: Any, max_len: int = 80) -> str:
    """Coerce to string, replace non-latin-1 chars, and truncate."""
    s = str(value or "")
    safe = s.encode("latin-1", errors="replace").decode("latin-1")
    return safe[:max_len]


def export_books_pdf(
    books: list[dict[str, Any]],
    title: str = "Iqra Book List",
) -> str:
    """
    Export books to a PDF file.

    Parameters
    ----------
    books : list of canonical book dicts (same schema as recommender output)
    title : page title printed at the top of the PDF

    Returns
    -------
    str
        Absolute path to the generated PDF file.
    """
    settings.artifact_dir.mkdir(parents=True, exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    out_path = settings.artifact_dir / f"export_{timestamp}.pdf"

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # ── Title block ───────────────────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(43, 92, 230)  # --primary
    pdf.cell(0, 12, _safe_str(title, 80), border=0, ln=1, align="C")
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(100, 100, 100)
    generated = datetime.now().strftime("%Y-%m-%d %H:%M")
    pdf.cell(
        0, 7,
        f"Generated by Iqra Digital Library  |  {generated}  |  {len(books)} books",
        border=0, ln=1, align="C",
    )
    pdf.ln(5)

    # ── Separator ─────────────────────────────────────────────────────────
    pdf.set_draw_color(43, 92, 230)
    pdf.set_line_width(0.6)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(4)

    # ── Table header ──────────────────────────────────────────────────────
    col_w: list[float] = [8, 72, 52, 18, 18, 22]
    headers: list[str] = ["#", "Title", "Authors", "Rating", "Year", "Pages"]

    pdf.set_fill_color(43, 92, 230)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 8)
    for w, h in zip(col_w, headers):
        pdf.cell(w, 9, h, border=1, fill=True)
    pdf.ln()

    # ── Table rows ────────────────────────────────────────────────────────
    pdf.set_font("Helvetica", "", 8)
    for i, book in enumerate(books, start=1):
        fill = i % 2 == 0
        if fill:
            pdf.set_fill_color(238, 242, 255)  # --primary-lt
        else:
            pdf.set_fill_color(255, 255, 255)

        pdf.set_text_color(15, 23, 42)  # --text

        num_text     = str(i)
        title_text   = _safe_str(book.get("title",   ""), 58)
        authors_text = _safe_str(book.get("authors", ""), 40)
        rating_val   = float(book.get("average_rating", 0.0) or 0.0)
        rating_text  = f"{rating_val:.1f}"
        year_text    = _safe_str(book.get("published_year", ""), 6)
        pages_val    = int(float(book.get("num_pages", 0) or 0))
        pages_text   = str(pages_val) if pages_val else ""

        pdf.cell(col_w[0], 8, num_text,     border=1, fill=fill, align="C")
        pdf.cell(col_w[1], 8, title_text,   border=1, fill=fill)
        pdf.cell(col_w[2], 8, authors_text, border=1, fill=fill)
        pdf.cell(col_w[3], 8, rating_text,  border=1, fill=fill, align="C")
        pdf.cell(col_w[4], 8, year_text,    border=1, fill=fill, align="C")
        pdf.cell(col_w[5], 8, pages_text,   border=1, fill=fill, align="C")
        pdf.ln()

    # ── Footer note ───────────────────────────────────────────────────────
    pdf.ln(4)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(148, 163, 184)
    pdf.cell(
        0, 6, "Iqra Digital Library — powered by FAISS + SentenceTransformers",
        border=0, ln=1, align="C",
    )

    pdf.output(str(out_path))
    logger.info("PDF exported: %s  (%d books)", out_path, len(books))
    return str(out_path)
